apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-public-api-1-deployment
  labels:
    app: ecommerce-public-api-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecommerce-public-api-1
  template:
    metadata:
      labels:
        app: ecommerce-public-api-1
    spec:
      containers:
        - name: ecommerce-public-api-1
          image: 145785214025.dkr.ecr.ap-south-1.amazonaws.com/development/promotion-assessment/ecommerce-public-api-1:latest
          ports:
            - containerPort: 80
