apiVersion: v1
kind: Secret
metadata:
  name: pgsql-secret
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: TmFncEAyMDIz
  dbconnstring: VXNlciBJRCA9cG9zdGdyZXM7UGFzc3dvcmQ9TmFncEAyMDIzO1NlcnZlcj1sb2NhbGhvc3Q7UG9ydD01NDMyO0RhdGFiYXNlPW5hZ3BnOyBJbnRlZ3JhdGVkIFNlY3VyaXR5PXRydWU7UG9vbGluZz10cnVlOw==